In [2]:
import pandas as pd
import numpy as np
import gc

train = pd.read_csv("train.csv", 
                    usecols=["node1_id", "node2_id", "is_chat"], 
                    dtype={"node1_id": np.int64, "node2_id":np.int64, "is_chat": np.int8},nrows=50)
test = pd.read_csv("test.csv", 
                    usecols=["id", "node1_id", "node2_id"], 
                    dtype={"id": np.int64, "node1_id": np.int64, "node2_id":np.int64},nrows=50)

node1 = train.groupby("node1_id", as_index=False)["is_chat"].mean()
node2 = train.groupby("node2_id", as_index=False)["is_chat"].mean()
train.head(10)
#el train
gc.collect()

test = (test.merge(node1, on="node1_id", how="left")
            .merge(node2, on="node2_id", how="left", suffixes=('_1', '_2')))

test["is_chat"] = test["is_chat_1"].fillna(0)*0.5 + test["is_chat_2"].fillna(0)*0.5
test[["id", "is_chat"]].to_csv("submit.csv", index=False)

In [3]:
train.head(10)

   node1_id  node2_id  is_chat
0   8446602   6636127        0
1   1430102   7433949        0
2   2803017   8372333        0
3   4529348    894645        0
4   5096572   4211638        0
5   8325853   1305287        0
6   7218175    120961        0
7   7159649   7791327        1
8   4481049   7514725        0
9   2232007   4102278        0